server:
  port: 8080


spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8090/
          predicates:
            - Path=/order-service/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<path>,*), /$\{path}

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=auth
    username: postgres
    password: postgres