server:
    port: 8081
    forward-headers-strategy: framework

spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
    jpa:
        generate-ddl: true
