spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
    jpa:
        generate-ddl: true
    rabbitmq:
        host: 127.0.0.1
        password: guest
        port: 5672
        username: guest

    springdoc:
        show-actuator: true
        swagger-ui:
            enabled: true
            path: /swagger-ui.html
#    mvc:
#        pathmatch:
#            matching-strategy: ANT_PATH-MATCHER
